import sys 

def display_usage(name):
    print "Usage: python " + name + " input_file [output_file]"

def filter_garbage(input_file, output=None):
    """Remove all the garbage tweets generated by the runtracker apps"""
    if output != None:
        out = open(output, 'w')
    result = ""
    with open(input_file) as f:
        for line in f:
            if line.find("#WorldRankin") == -1:
                result += line
                if output == None:
                    sys.stdout.write(line)
                    sys.stdout.flush()
                else:
                    out.write(line)
    if output != None:
        out.close()
    return result

if __name__ == "__main__":
    nbargs = len(sys.argv)
    less_garbage = ""
    if nbargs <= 1 or nbargs > 3: # Wrong usage
        display_usage(sys.argv[0])
        exit()
    elif nbargs == 2:
        less_garbage = filter_garbage(sys.argv[1])
    else:
        less_garbage = filter_garbage(sys.argv[1], sys.argv[2])


